name: inutriguide-prod-build

services:
  backend:
    image: ${DOCKER_IMAGE_NAMESPACE:-wakilrh}/inutriguide-backend:${IMAGE_TAG:-latest}
    build:
      context: ./apps/backend
      target: production
      cache_from:
        - ${DOCKER_IMAGE_NAMESPACE:-wakilrh}/inutriguide-backend:${CACHE_TAG:-latest}
    platform: ${DOCKER_PLATFORM:-linux/amd64}

  admin_panel:
    image: ${DOCKER_IMAGE_NAMESPACE:-wakilrh}/inutriguide-admin-panel:${IMAGE_TAG:-latest}
    build:
      context: ./apps/admin-panel
      target: production
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://34.155.56.156/api/v1}
      cache_from:
        - ${DOCKER_IMAGE_NAMESPACE:-wakilrh}/inutriguide-admin-panel:${CACHE_TAG:-latest}
    platform: ${DOCKER_PLATFORM:-linux/amd64}
