services:
  postgres:
    ports: !override
      - "15432:5432"

  redis:
    ports: !override
      - "16379:6379"

  backend:
    ports: !override
      - "18000:8000"

  admin_panel:
    ports: !override
      - "15173:5173"

  dozzle:
    ports: !override
      - "19999:8080"
