# Generated by Django 5.1.15 on 2026-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_dailytracking_profile_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
