# Generated by Django 5.1.15 on 2026-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytracking",
            name="food_entries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
