# Generated by Django 5.1.15 on 2026-05-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplementDataImportCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=80, unique=True)),
                ("cursor", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source"],
            },
        ),
        migrations.CreateModel(
            name="SupplementIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="NIH DSLD", max_length=80)),
                ("source_id", models.CharField(blank=True, max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("ingredient_group", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "percent_daily_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "serving_size_order",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_other_ingredient", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["supplement__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplementIngredientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="NIH DSLD", max_length=80)),
                ("source_id", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=180)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("fact_sheets", models.JSONField(blank=True, default=list)),
                ("nutrient_info", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplementLabelStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="NIH DSLD", max_length=80)),
                ("statement_type", models.CharField(max_length=160)),
                ("text", models.TextField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["supplement__name", "statement_type"],
            },
        ),
        migrations.CreateModel(
            name="SupplementResearchEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="NIH DSID", max_length=80)),
                ("release", models.CharField(default="DSID-4", max_length=40)),
                ("table_name", models.CharField(default="Table2", max_length=80)),
                ("study_code", models.CharField(blank=True, max_length=40)),
                ("ingredient_name", models.CharField(max_length=180)),
                ("ingredient_key", models.SlugField(max_length=180)),
                (
                    "labeled_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("labeled_unit", models.CharField(blank=True, max_length=40)),
                (
                    "predicted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("predicted_unit", models.CharField(blank=True, max_length=40)),
                (
                    "predicted_percent_difference",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "standard_error_mean",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "standard_error_observation",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("linking_code", models.CharField(blank=True, max_length=120)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ingredient_name", "labeled_amount"],
            },
        ),
        migrations.AddField(
            model_name="supplement",
            name="brand_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="supplement",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="supplement",
            name="off_market",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplement",
            name="physical_state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplement",
            name="product_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplement",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="supplement",
            name="source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="supplement",
            name="source_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplement",
            name="target_groups",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="supplement",
            name="upc",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="supplement",
            index=models.Index(
                fields=["source", "source_id"], name="supplemen_s_source_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplement",
            index=models.Index(fields=["brand_name"], name="supplemen_s_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="supplement",
            index=models.Index(
                fields=["product_type"], name="supplemen_s_product_type_idx"
            ),
        ),
        migrations.AddField(
            model_name="supplementingredient",
            name="supplement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_ingredients",
                to="supplements.supplement",
            ),
        ),
        migrations.AddIndex(
            model_name="supplementingredientgroup",
            index=models.Index(fields=["slug"], name="supp_group_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementingredientgroup",
            index=models.Index(
                fields=["source", "source_id"], name="supp_group_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementingredientgroup",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"),
                name="unique_supplement_ingredient_group",
            ),
        ),
        migrations.AddField(
            model_name="supplementlabelstatement",
            name="supplement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_statements",
                to="supplements.supplement",
            ),
        ),
        migrations.AddIndex(
            model_name="supplementresearchestimate",
            index=models.Index(
                fields=["source", "release"], name="supp_est_source_release_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementresearchestimate",
            index=models.Index(
                fields=["ingredient_key"], name="supp_est_ingredient_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementresearchestimate",
            index=models.Index(fields=["study_code"], name="supp_est_study_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementresearchestimate",
            index=models.Index(fields=["linking_code"], name="supp_est_linking_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplementresearchestimate",
            constraint=models.UniqueConstraint(
                fields=("source", "release", "table_name", "linking_code"),
                name="unique_supplement_research_estimate",
            ),
        ),
        migrations.AddIndex(
            model_name="supplementingredient",
            index=models.Index(
                fields=["source", "source_id"], name="supp_ing_source_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementingredient",
            index=models.Index(fields=["ingredient_group"], name="supp_ing_group_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementingredient",
            index=models.Index(fields=["category"], name="supp_ing_category_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplementingredient",
            constraint=models.UniqueConstraint(
                fields=(
                    "supplement",
                    "source",
                    "source_id",
                    "name",
                    "is_other_ingredient",
                ),
                name="unique_supplement_label_ingredient",
            ),
        ),
        migrations.AddIndex(
            model_name="supplementlabelstatement",
            index=models.Index(
                fields=["source", "statement_type"], name="supp_stmt_source_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplementlabelstatement",
            constraint=models.UniqueConstraint(
                fields=("supplement", "source", "statement_type", "text"),
                name="unique_supplement_label_statement",
            ),
        ),
    ]
