# Generated by Django 5.1.15 on 2026-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplements",
            "0002_supplementdataimportcheckpoint_supplementingredient_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplementFactSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="NIH ODS", max_length=80)),
                ("source_id", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("consumer", "Consumer"),
                            ("health_professional", "Health Professional"),
                        ],
                        default="consumer",
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("safety", models.TextField(blank=True)),
                ("interactions", models.TextField(blank=True)),
                ("recommended_intake", models.TextField(blank=True)),
                ("deficiency", models.TextField(blank=True)),
                ("food_sources", models.TextField(blank=True)),
                ("raw_sections", models.JSONField(blank=True, default=dict)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "audience"],
            },
        ),
        migrations.DeleteModel(
            name="SupplementIngredientGroup",
        ),
        migrations.DeleteModel(
            name="SupplementResearchEstimate",
        ),
        migrations.RemoveIndex(
            model_name="supplement",
            name="supplemen_s_brand_idx",
        ),
        migrations.RemoveIndex(
            model_name="supplement",
            name="supplemen_s_product_type_idx",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="off_market",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="physical_state",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="raw_data",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="target_groups",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="upc",
        ),
        migrations.AddIndex(
            model_name="supplementfactsheet",
            index=models.Index(
                fields=["source", "source_id"], name="supp_fact_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementfactsheet",
            index=models.Index(fields=["audience"], name="supp_fact_audience_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementfactsheet",
            index=models.Index(fields=["slug"], name="supp_fact_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplementfactsheet",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id", "audience"),
                name="unique_supplement_fact_sheet",
            ),
        ),
        migrations.DeleteModel(
            name="SupplementIngredient",
        ),
        migrations.DeleteModel(
            name="SupplementLabelStatement",
        ),
    ]
