# Generated by Django 5.1.15 on 2026-05-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_ciqual_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="allergen_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="association_rule_items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="avoid_or_caution",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="food",
            name="diet_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="food",
            name="image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="food",
            name="nutrient_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="recommended_for_supplements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="food",
            name="synergy_reason",
            field=models.TextField(blank=True),
        ),
    ]
