entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  bolt:
    address: ":7687"

providers:
  docker:
    exposedByDefault: false
    network: inutriguide-prod_public
  file:
    filename: /etc/traefik/dynamic.yml

api:
  dashboard: false
  insecure: false

ping: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@matchcesoir.pro
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
